openapi: 3.0.0
paths:
  /auth/github:
    get:
      operationId: AuthController_redirectToGitHubAuthorizePage
      parameters: []
      responses:
        '200':
          description: ''
  /auth/github/code:
    post:
      operationId: AuthController_signInWithGitHub
      parameters:
        - name: code
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInWithGitHubResponse'
  /user/example:
    get:
      operationId: UserController_example
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: '@monju/api'
  description: ''
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  schemas:
    SignInWithGitHubResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
