name = "r2-worker"
main = "src/index.ts"
compatibility_date = "2022-07-10"

account_id = "44dc347a58d3934d0268aa8d8f51ae85"
workers_dev = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'my-bucket'
